const KeyTable = {
  smg: 'SMG',
  assault: 'Assault',
  pistol: 'Pistol',
  mac10: 'MAC-10',
  mp5: 'MP5',
  mp7: 'MP7',
  krissVector: 'KRISS Vector',
  ak47: 'AK-47',
  scar17: 'SCAR-17',
  m4: 'M4',
  1911: '1911',
  glock: 'Glock',
  sig: 'Sig',
  beretta: 'Beretta',
  desertEagle: 'Desert Eagle',
  'SMG': 'smg',
  'Assault': 'assault',
  'Pistol': 'pistol',
  'MAC-10': 'mac10',
  'MP5': 'mp5',
  'MP7': 'mp7',
  'KRISS Vector': 'krissVector',
  'AK-47': 'ak47',
  'SCAR-17': 'scar17',
  'M4': 'm4',
  'Glock': 'glock',
  'Sig': 'sig',
  'Beretta': 'beretta',
  'Desert Eagle': 'desertEagle',
  primary: 'Primary',
  secondary: 'Secondary',
  'Primary': 'primary',
  'Secondary': 'secondary',
}

export default KeyTable;
