const KeyTable = {
  smg: 'SMG',
  assault: 'Assault',
  pistol: 'Pistol',
  mac10: 'MAC-10',
  mp5: 'MP5',
  mp7: 'MP7',
  krissVector: 'KRISS Vector',
  ak47: 'AK-47',
  fnScar: 'FN-SCAR',
  m4: 'M4',
  m16: 'M16',
  ar15: 'AR-15',
  1911: '1911',
  glock: 'Glock',
  sig: 'Sig',
  beretta: 'Beretta',
  desertEagle: 'Desert Eagle',
  aap01: 'AAP-01',
  'AAP-01': 'aap01',
  'SMG': 'smg',
  'Assault': 'assault',
  'Pistol': 'pistol',
  'MAC-10': 'mac10',
  'MP5': 'mp5',
  'MP7': 'mp7',
  'KRISS Vector': 'krissVector',
  'AK-47': 'ak47',
  'FN-SCAR': 'fnScar',
  'M4': 'm4',
  'AR-15': 'ar15',
  'M16': 'm16',
  'Glock': 'glock',
  'Sig': 'sig',
  'Beretta': 'beretta',
  'Desert Eagle': 'desertEagle',
  primary: 'Primary Weapon',
  secondary: 'Secondary Weapon',
  'Primary Weapon': 'primary',
  'Secondary Weapon': 'secondary',
}

export default KeyTable;
